### ISSUE TITLE
BigQuery API is called too many times

### ISSUE THREAD

**Issue by spark2ignite** [doitintl/iris#17]
Looks like we are calling BigQuery API too many times on each table and because of that we are exhausting API rate limits.

Links to the [relevant log](https://console.cloud.google.com/logs/viewer?project=taboola-iris&organizationId=78418439000&minLogLevel=0&expandAll=false&timestamp=2018-07-03T14%3A42%3A17.313000000Z&customFacets&limitCustomFacetWidth=false&dateRangeStart=2018-07-03T13%3A42%3A17.563Z&dateRangeEnd=2018-07-03T14%3A42%3A17.563Z&interval=PT1H&resource=gae_app&scrollTimestamp=2018-07-03T14%3A40%3A17.660701000Z&logName=projects%2Ftaboola-iris%2Flogs%2Fappengine.googleapis.com%252Frequest_log&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.version_id%3D%2220180703t171229%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.zone%3D%22us12%22%0Aresource.labels.project_id%3D%22taboola-iris%22%0Atimestamp%3D%222018-07-03T14%3A40%3A17.648744000Z%22%0AinsertId%3D%225b3b8b190008e549c88c6b96%22)

**Comment by avivl** [comment]
@spark2ignite nothing special , why do you think that we are calling too many times?
